version: "3"
services:
  gestion:
    build: .
    container_name: bijoux-tendances_gestion
    restart: unless-stopped
    ports:
      - "7000:7000"
    networks:
      - reverse-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gestion.rule=Host(`gestion.idtendances.com`)"
      - "traefik.http.services.gestion.loadbalancer.server.port=7000"

networks:
  reverse-proxy:
    name: reverse-proxy
    external: true
